"""Reviewed V1 question bank. Each skill has four questions; the first two are diagnostic."""

QUESTIONS = [
    {
        "id": 1, "skill": "inspection", "difficulty": 1,
        "prompt": "Which expression gives the number of rows and columns in df?",
        "code": "df = pd.DataFrame({'a': [1, 2], 'b': [3, 4]})",
        "options": {"A": "df.size", "B": "df.shape", "C": "df.count()", "D": "df.info()"},
        "answer": "B", "explanation": "df.shape returns a tuple: (number_of_rows, number_of_columns).",
    },
    {
        "id": 2, "skill": "inspection", "difficulty": 2,
        "prompt": "Which method is most useful for seeing column names, non-null counts and dtypes together?",
        "options": {"A": "df.head()", "B": "df.describe()", "C": "df.info()", "D": "df.sample()"},
        "answer": "C", "explanation": "df.info() provides a compact structural summary including non-null counts and dtypes.",
    },
    {
        "id": 3, "skill": "inspection", "difficulty": 2,
        "prompt": "What does df.nunique(dropna=True) return?",
        "options": {"A": "Unique rows", "B": "Unique non-null values per column", "C": "Duplicate counts", "D": "Only numeric columns"},
        "answer": "B", "explanation": "nunique counts distinct values for each column; dropna=True excludes missing values.",
    },
    {
        "id": 4, "skill": "inspection", "difficulty": 2,
        "prompt": "Which expression returns the percentage of missing values in every column?",
        "options": {"A": "df.isna().mean() * 100", "B": "df.isna().count()", "C": "df.mean().isna()", "D": "df.nulls() / 100"},
        "answer": "A", "explanation": "Booleans behave like 1 and 0 in mean(), so the mean of isna() is the missing fraction.",
    },
    {
        "id": 5, "skill": "missing", "difficulty": 1,
        "prompt": "Which expression counts missing values in each column?",
        "options": {"A": "df.isna().sum()", "B": "df.count().isna()", "C": "df.dropna().sum()", "D": "df.empty()"},
        "answer": "A", "explanation": "isna() creates a Boolean mask and sum() counts True values column by column.",
    },
    {
        "id": 6, "skill": "missing", "difficulty": 2,
        "prompt": "You want to fill missing salary values with the median salary. Which is correct?",
        "options": {"A": "df['salary'].fillna(df['salary'].median())", "B": "df['salary'].dropna('median')", "C": "df.fillna.salary.median()", "D": "df['salary'].replace(df.median)"},
        "answer": "A", "explanation": "Compute the Series median, then pass that scalar into fillna(). Assign the result if you want to retain it.",
    },
    {
        "id": 7, "skill": "missing", "difficulty": 2,
        "prompt": "What does df.dropna(how='all') remove?",
        "options": {"A": "Rows with any missing value", "B": "Columns with missing values", "C": "Rows where every value is missing", "D": "All missing cells only"},
        "answer": "C", "explanation": "how='all' requires every value on the selected axis to be missing before dropping it.",
    },
    {
        "id": 8, "skill": "missing", "difficulty": 3,
        "prompt": "Which operation fills missing values using the previous valid value down each column?",
        "options": {"A": "df.ffill()", "B": "df.bfill(axis=1)", "C": "df.interpolate(False)", "D": "df.shift()"},
        "answer": "A", "explanation": "ffill propagates the last valid observation forward. Use it only when row order has meaning.",
    },
    {
        "id": 9, "skill": "duplicates", "difficulty": 1,
        "prompt": "Which expression counts fully duplicated rows?",
        "options": {"A": "df.duplicated().sum()", "B": "df.drop_duplicates().count()", "C": "df.unique().sum()", "D": "df.value_counts().shape"},
        "answer": "A", "explanation": "duplicated() flags repeated rows after the first occurrence; sum() counts them.",
    },
    {
        "id": 10, "skill": "duplicates", "difficulty": 2,
        "prompt": "Keep the latest row for each customer_id. Which call is appropriate after sorting by date?",
        "options": {"A": "df.drop_duplicates('customer_id', keep='last')", "B": "df.unique('customer_id')", "C": "df.dropna('customer_id')", "D": "df.groupby('customer_id').drop()"},
        "answer": "A", "explanation": "After sorting chronologically, keep='last' retains the latest occurrence for each customer.",
    },
    {
        "id": 11, "skill": "duplicates", "difficulty": 2,
        "prompt": "How do you flag every member of a duplicate email group, including its first row?",
        "options": {"A": "df.duplicated('email')", "B": "df.duplicated('email', keep=False)", "C": "df['email'].unique()", "D": "df.drop_duplicates('email')"},
        "answer": "B", "explanation": "keep=False marks all occurrences of duplicated values rather than preserving one as False.",
    },
    {
        "id": 12, "skill": "duplicates", "difficulty": 3,
        "prompt": "Which subset removes duplicates only when customer_id and transaction_date both match?",
        "options": {"A": "df.drop_duplicates()", "B": "df.drop_duplicates(['customer_id', 'transaction_date'])", "C": "df.drop_duplicates('customer_id' and 'transaction_date')", "D": "df.unique(axis=2)"},
        "answer": "B", "explanation": "Pass a list of column names to subset so the combination defines a duplicate.",
    },
    {
        "id": 13, "skill": "types", "difficulty": 1,
        "prompt": "Which function safely converts invalid numeric strings to NaN?",
        "options": {"A": "pd.to_numeric(s, errors='coerce')", "B": "s.astype(int)", "C": "pd.numeric(s, ignore=True)", "D": "s.convert('number')"},
        "answer": "A", "explanation": "errors='coerce' replaces values that cannot be parsed with NaN instead of raising an exception.",
    },
    {
        "id": 14, "skill": "types", "difficulty": 2,
        "prompt": "Which expression converts a date column while flagging invalid dates as missing?",
        "options": {"A": "pd.to_datetime(df['date'], errors='coerce')", "B": "df['date'].astype(date)", "C": "pd.date(df['date'])", "D": "df['date'].parse()"},
        "answer": "A", "explanation": "to_datetime performs date parsing; coercion turns invalid values into NaT.",
    },
    {
        "id": 15, "skill": "types", "difficulty": 2,
        "prompt": "Why might astype(int) fail on a numeric-looking column?",
        "options": {"A": "Integers are unsupported", "B": "The column may contain NaN or invalid strings", "C": "astype only works on indexes", "D": "Pandas always stores numbers as text"},
        "answer": "B", "explanation": "Missing values and strings such as 'N/A' cannot be directly converted to standard int.",
    },
    {
        "id": 16, "skill": "types", "difficulty": 3,
        "prompt": "What is the main advantage of df.convert_dtypes()?",
        "options": {"A": "It deletes invalid rows", "B": "It infers better nullable Pandas dtypes", "C": "It converts everything to float", "D": "It normalizes all values"},
        "answer": "B", "explanation": "convert_dtypes prefers nullable extension types such as Int64, string and boolean where possible.",
    },
    {
        "id": 17, "skill": "text", "difficulty": 1,
        "prompt": "How do you remove surrounding whitespace from a text column?",
        "options": {"A": "df['name'].str.strip()", "B": "df['name'].strip()", "C": "strip(df['name'])", "D": "df.trim('name')"},
        "answer": "A", "explanation": "The .str accessor applies vectorized string operations to a Series.",
    },
    {
        "id": 18, "skill": "text", "difficulty": 2,
        "prompt": "Which chain standardizes emails by trimming spaces and lowercasing?",
        "options": {"A": "s.str.strip().str.lower()", "B": "s.strip().lower()", "C": "s.lower().trim()", "D": "pd.lower(s, strip=True)"},
        "answer": "A", "explanation": "Both operations use the vectorized .str accessor and can be chained.",
    },
    {
        "id": 19, "skill": "text", "difficulty": 2,
        "prompt": "Which expression replaces repeated whitespace inside strings with one space?",
        "options": {"A": "s.str.replace(r'\\s+', ' ', regex=True)", "B": "s.replace('  ', '')", "C": "s.str.strip('all')", "D": "s.collapse_spaces()"},
        "answer": "A", "explanation": "The regular expression \\s+ matches one or more whitespace characters.",
    },
    {
        "id": 20, "skill": "text", "difficulty": 3,
        "prompt": "What does s.str.contains('bank', case=False, na=False) produce?",
        "options": {"A": "A filtered DataFrame", "B": "A Boolean Series", "C": "A count of matches", "D": "A cleaned string Series"},
        "answer": "B", "explanation": "str.contains returns a Boolean mask; use it inside df[...] to filter rows.",
    },
    {
        "id": 21, "skill": "filtering", "difficulty": 1,
        "prompt": "Which expression selects rows where amount is positive and status is Approved?",
        "options": {"A": "df[(df['amount'] > 0) & (df['status'] == 'Approved')]", "B": "df[df['amount'] > 0 and df['status'] == 'Approved']", "C": "df.where('amount' > 0)", "D": "df.filter(amount=True)"},
        "answer": "A", "explanation": "Pandas combines Boolean Series with & and requires parentheses around each condition.",
    },
    {
        "id": 22, "skill": "filtering", "difficulty": 2,
        "prompt": "How do you replace values 'N/A' and '-' with missing values throughout df?",
        "options": {"A": "df.replace(['N/A', '-'], pd.NA)", "B": "df.fillna(['N/A', '-'])", "C": "df.drop(['N/A', '-'])", "D": "df.isna('N/A', '-')"},
        "answer": "A", "explanation": "replace maps specified sentinel strings to a consistent missing-value marker.",
    },
    {
        "id": 23, "skill": "filtering", "difficulty": 2,
        "prompt": "Which method is best for keeping rows whose category is A, B or C?",
        "options": {"A": "df[df['category'].isin(['A', 'B', 'C'])]", "B": "df[df['category'] in ['A', 'B', 'C']]", "C": "df.contains(['A', 'B', 'C'])", "D": "df.filter(category='A|B|C')"},
        "answer": "A", "explanation": "Series.isin returns an element-wise Boolean mask for membership in a collection.",
    },
    {
        "id": 24, "skill": "filtering", "difficulty": 3,
        "prompt": "What is the safest way to update only negative balances to zero?",
        "options": {"A": "df.loc[df['balance'] < 0, 'balance'] = 0", "B": "df[df['balance'] < 0]['balance'] = 0", "C": "df.balance.replace(all, 0)", "D": "df.iloc['balance' < 0] = 0"},
        "answer": "A", "explanation": ".loc combines row selection and column assignment, avoiding chained-assignment ambiguity.",
    },
    {
        "id": 25, "skill": "outliers", "difficulty": 2,
        "prompt": "In the IQR rule, a common lower outlier boundary is:",
        "options": {"A": "Q1 - 1.5 × IQR", "B": "Mean - IQR", "C": "Q3 - Q1 × 1.5", "D": "Median - standard deviation"},
        "answer": "A", "explanation": "The conventional IQR fences are Q1 − 1.5×IQR and Q3 + 1.5×IQR.",
    },
    {
        "id": 26, "skill": "outliers", "difficulty": 2,
        "prompt": "Which method caps values to specified lower and upper bounds?",
        "options": {"A": "s.clip(lower, upper)", "B": "s.cut(lower, upper)", "C": "s.limit(lower, upper)", "D": "s.boundaries()"},
        "answer": "A", "explanation": "clip replaces observations below or above the bounds with the boundary values.",
    },
    {
        "id": 27, "skill": "outliers", "difficulty": 3,
        "prompt": "Why should outliers not automatically be deleted?",
        "options": {"A": "Pandas cannot delete them", "B": "They may be valid rare observations with business meaning", "C": "Outliers never affect analysis", "D": "All outliers become NaN automatically"},
        "answer": "B", "explanation": "An unusual value can be an error or a meaningful event; investigate its context before choosing treatment.",
    },
    {
        "id": 28, "skill": "outliers", "difficulty": 3,
        "prompt": "Which statistic is generally more robust to extreme values?",
        "options": {"A": "Mean", "B": "Median", "C": "Maximum", "D": "Range"},
        "answer": "B", "explanation": "The median depends on order rather than magnitude, so extreme values influence it less than the mean.",
    },
    {
        "id": 29, "skill": "joins", "difficulty": 2,
        "prompt": "Which merge keeps every row from the left DataFrame and matching rows from the right?",
        "options": {"A": "pd.merge(left, right, how='left', on='id')", "B": "pd.merge(left, right, how='inner', on='id')", "C": "left.concat(right)", "D": "pd.join(left, right, how='right')"},
        "answer": "A", "explanation": "A left join preserves all left keys and adds matching right-side values where available.",
    },
    {
        "id": 30, "skill": "joins", "difficulty": 2,
        "prompt": "Which option checks that each left key matches at most one right row?",
        "options": {"A": "validate='many_to_one'", "B": "verify='unique'", "C": "how='one'", "D": "duplicates=False"},
        "answer": "A", "explanation": "merge(validate='many_to_one') raises an error if the right-side keys are not unique.",
    },
    {
        "id": 31, "skill": "joins", "difficulty": 3,
        "prompt": "Which operation converts several measure columns into variable/value rows?",
        "options": {"A": "pd.melt()", "B": "pd.pivot()", "C": "pd.merge()", "D": "df.unstack(axis=0) only"},
        "answer": "A", "explanation": "melt reshapes wide data into a longer variable/value representation.",
    },
    {
        "id": 32, "skill": "joins", "difficulty": 3,
        "prompt": "A merge unexpectedly multiplies rows. What is the most likely cause?",
        "options": {"A": "Duplicate join keys create a many-to-many match", "B": "The indexes have names", "C": "One DataFrame has fewer columns", "D": "how='left' always doubles rows"},
        "answer": "A", "explanation": "When both sides repeat the same key, every matching combination is produced, increasing row count.",
    },
]
