"""Readable, reviewed V2 question bank for all three learning tracks."""

TRACK_LABELS = {
    "pandas": "Pandas & Data Cleaning",
    "terraform": "Terraform Foundations",
    "capital_markets": "Capital Markets",
}

SKILL_LABELS = {
    "pandas": {
        "pd_inspect": "Inspecting data", "pd_missing": "Missing values",
        "pd_duplicates": "Duplicates", "pd_types": "Data types",
        "pd_text": "Text cleaning", "pd_filter": "Filtering & replacement",
    },
    "terraform": {
        "tf_workflow": "Core workflow", "tf_resources": "Resources & providers",
        "tf_variables": "Variables & outputs", "tf_state": "State management",
        "tf_modules": "Modules", "tf_safety": "Planning & safety",
    },
    "capital_markets": {
        "cm_structure": "Market structure", "cm_equity": "Equities",
        "cm_bonds": "Fixed income", "cm_derivatives": "Derivatives",
        "cm_risk": "Risk & return", "cm_operations": "Trade lifecycle",
    },
}


def q(question_id, track, skill, prompt, options, answer, explanation, *, context="", code="", difficulty=2, diagnostic=False):
    keys = ["A", "B", "C", "D"]
    return {"id": question_id, "track": track, "skill": skill, "prompt": prompt,
            "context": context, "code": code, "options": dict(zip(keys, options)),
            "answer": keys[answer], "explanation": explanation,
            "difficulty": difficulty, "diagnostic": diagnostic}


QUESTIONS = [
    # Pandas — Ashutosh
    q(1, "pandas", "pd_inspect", "Which expression returns the number of rows and columns?",
      ["df.shape", "df.size", "df.count()", "df.info()"], 0,
      "df.shape returns a tuple in the form (rows, columns).", code="df = pd.DataFrame({'a': [1, 2], 'b': [3, 4]})", diagnostic=True),
    q(2, "pandas", "pd_inspect", "Which method shows column names, non-null counts and data types together?",
      ["df.head()", "df.info()", "df.describe()", "df.sample()"], 1,
      "df.info() is the quickest structural summary of a DataFrame.", diagnostic=True),
    q(3, "pandas", "pd_inspect", "How do you calculate the missing-value percentage for every column?",
      ["df.isna().mean() * 100", "df.isna().count()", "df.count() / 100", "df.nulls().mean()"], 0,
      "isna() creates booleans; their mean is the missing fraction."),
    q(4, "pandas", "pd_missing", "Which expression counts missing values in each column?",
      ["df.isna().sum()", "df.dropna().sum()", "df.count().isna()", "df.empty()"], 0,
      "isna() marks missing cells and sum() counts the True values.", diagnostic=True),
    q(5, "pandas", "pd_missing", "How should missing salary values be replaced with the median salary?",
      ["df['salary'].fillna(df['salary'].median())", "df['salary'].dropna('median')", "df.fillna.salary.median()", "df['salary'].replace(df.median)"], 0,
      "Calculate the Series median and pass that scalar to fillna().", diagnostic=True),
    q(6, "pandas", "pd_missing", "What does this operation remove?",
      ["Rows containing any missing value", "Rows where every value is missing", "Columns containing missing values", "Only the missing cells"], 1,
      "how='all' drops a row only when every value in it is missing.", code="df.dropna(how='all')"),
    q(7, "pandas", "pd_duplicates", "Which expression counts fully duplicated rows?",
      ["df.duplicated().sum()", "df.drop_duplicates().count()", "df.unique().sum()", "df.value_counts().shape"], 0,
      "duplicated() flags repeated rows after the first occurrence.", diagnostic=True),
    q(8, "pandas", "pd_duplicates", "After sorting by date, how do you retain the latest row for each customer?",
      ["df.drop_duplicates('customer_id', keep='last')", "df.unique('customer_id')", "df.dropna('customer_id')", "df.groupby('customer_id').drop()"], 0,
      "keep='last' retains the final occurrence of each customer ID.", diagnostic=True),
    q(9, "pandas", "pd_duplicates", "How do you flag every row belonging to a duplicated email group?",
      ["df.duplicated('email')", "df.duplicated('email', keep=False)", "df['email'].unique()", "df.drop_duplicates('email')"], 1,
      "keep=False marks all members of each duplicate group, including the first."),
    q(10, "pandas", "pd_types", "Which expression converts invalid numeric strings into missing values?",
      ["pd.to_numeric(s, errors='coerce')", "s.astype(int)", "pd.numeric(s, ignore=True)", "s.convert('number')"], 0,
      "errors='coerce' converts unparseable values to NaN.", diagnostic=True),
    q(11, "pandas", "pd_types", "How do you parse a date column while turning invalid dates into NaT?",
      ["pd.to_datetime(df['date'], errors='coerce')", "df['date'].astype(date)", "pd.date(df['date'])", "df['date'].parse()"], 0,
      "to_datetime performs date parsing; coercion safely marks invalid entries.", diagnostic=True),
    q(12, "pandas", "pd_types", "Why can astype(int) fail on a numeric-looking column?",
      ["Integers are unsupported", "The column contains NaN or invalid strings", "astype works only on indexes", "Pandas stores every number as text"], 1,
      "Standard integers cannot directly represent NaN, and invalid strings cannot be parsed."),
    q(13, "pandas", "pd_text", "How do you remove surrounding whitespace from every value in a text column?",
      ["df['name'].str.strip()", "df['name'].strip()", "strip(df['name'])", "df.trim('name')"], 0,
      "The .str accessor applies vectorized string methods to a Series.", diagnostic=True),
    q(14, "pandas", "pd_text", "Which chain trims spaces and lowercases every email address?",
      ["s.str.strip().str.lower()", "s.strip().lower()", "s.lower().trim()", "pd.lower(s, strip=True)"], 0,
      "Both vectorized operations use the Series .str accessor.", diagnostic=True),
    q(15, "pandas", "pd_text", "What does this expression return?",
      ["A filtered DataFrame", "A Boolean Series", "A count of matches", "A cleaned text Series"], 1,
      "str.contains returns a Boolean mask that can then filter rows.", code="df['company'].str.contains('bank', case=False, na=False)"),
    q(16, "pandas", "pd_filter", "Which expression keeps positive amounts with an Approved status?",
      ["df[(df['amount'] > 0) & (df['status'] == 'Approved')]", "df[df['amount'] > 0 and df['status'] == 'Approved']", "df.where('amount' > 0)", "df.filter(amount=True)"], 0,
      "Pandas combines Boolean Series with & and requires each condition in parentheses.", diagnostic=True),
    q(17, "pandas", "pd_filter", "How do you standardize both 'N/A' and '-' as missing values?",
      ["df.replace(['N/A', '-'], pd.NA)", "df.fillna(['N/A', '-'])", "df.drop(['N/A', '-'])", "df.isna('N/A', '-')"], 0,
      "replace maps several sentinel values to one missing marker.", diagnostic=True),
    q(18, "pandas", "pd_filter", "What is the safest way to set only negative balances to zero?",
      ["df.loc[df['balance'] < 0, 'balance'] = 0", "df[df['balance'] < 0]['balance'] = 0", "df.balance.replace(all, 0)", "df.iloc['balance' < 0] = 0"], 0,
      ".loc performs selection and assignment together, avoiding chained assignment."),

    # Terraform — Aakash
    q(101, "terraform", "tf_workflow", "Which command prepares a new Terraform working directory?",
      ["terraform init", "terraform plan", "terraform apply", "terraform validate"], 0,
      "terraform init initializes the directory and installs required providers and modules.", diagnostic=True),
    q(102, "terraform", "tf_workflow", "Which command previews infrastructure changes without applying them?",
      ["terraform plan", "terraform show", "terraform apply", "terraform state list"], 0,
      "terraform plan creates an execution plan but does not perform the proposed changes.", diagnostic=True),
    q(103, "terraform", "tf_workflow", "Which is the usual safe workflow after editing configuration?",
      ["init → validate → plan → apply", "apply → init → destroy", "plan → format → import", "state list → destroy → apply"], 0,
      "Initialize when needed, validate syntax, inspect a plan, and apply approved changes."),
    q(104, "terraform", "tf_resources", "What does a resource block represent?",
      ["An infrastructure object Terraform manages", "Only a local variable", "A provider login session", "A saved execution plan"], 0,
      "A resource block declares an infrastructure object and its desired configuration.", diagnostic=True),
    q(105, "terraform", "tf_resources", "What is the purpose of a provider?",
      ["Connect Terraform to an external platform API", "Store only output values", "Replace the state file", "Format HCL"], 0,
      "Providers implement resource types and API operations for platforms such as AWS.", diagnostic=True),
    q(106, "terraform", "tf_resources", "What does this resource address mean?",
      ["The web resource of type aws_instance", "An AWS provider called web", "A module named instance", "A variable containing an EC2 ID"], 0,
      "Terraform resource addresses use resource_type.resource_name.", code="aws_instance.web"),
    q(107, "terraform", "tf_variables", "Why define an input variable?",
      ["Parameterize reusable configuration", "Save provider plugins", "Create state automatically", "Delete repeated resources"], 0,
      "Variables let callers change values without editing a module's source.", diagnostic=True),
    q(108, "terraform", "tf_variables", "What is the main purpose of an output block?",
      ["Expose useful values from a module", "Store secrets outside state", "Install a provider", "Approve a plan"], 0,
      "Outputs expose values to the CLI, parent modules or automation.", diagnostic=True),
    q(109, "terraform", "tf_variables", "How is the input variable named region referenced?",
      ["var.region", "variable.region", "input.region", "terraform.region"], 0,
      "Input variables use the var.<name> expression.", code='variable "region" { type = string }'),
    q(110, "terraform", "tf_state", "What is Terraform state primarily used for?",
      ["Map configuration to managed real-world objects", "Store HCL comments", "Replace cloud monitoring", "Encrypt every secret automatically"], 0,
      "State records the relationship between resource addresses and remote objects.", diagnostic=True),
    q(111, "terraform", "tf_state", "Why is shared remote state preferable for a team?",
      ["It provides a common location and can support locking", "It removes the need for providers", "It makes every apply automatic", "It stores code instead of Git"], 0,
      "A shared backend reduces conflicting local copies and can coordinate access.", diagnostic=True),
    q(112, "terraform", "tf_state", "Which command lists resources currently recorded in state?",
      ["terraform state list", "terraform state apply", "terraform resource show", "terraform list plan"], 0,
      "terraform state list displays resource addresses in the current state."),
    q(113, "terraform", "tf_modules", "What is a Terraform module?",
      ["A collection of resources managed together", "A state backup only", "A provider binary", "A cloud account"], 0,
      "A module groups related configuration into a reusable unit.", diagnostic=True),
    q(114, "terraform", "tf_modules", "Which argument tells a module block where its code comes from?",
      ["source", "provider", "backend", "path_id"], 0,
      "source identifies a local path, registry module or supported remote source.", diagnostic=True),
    q(115, "terraform", "tf_modules", "How does a parent module access the child output named vpc_id?",
      ["module.network.vpc_id", "var.network.vpc_id", "output.network.vpc_id", "resource.network.vpc_id"], 0,
      "Child outputs use module.<module_name>.<output_name>."),
    q(116, "terraform", "tf_safety", "Why save a plan with terraform plan -out=tfplan?",
      ["Apply the exact reviewed plan later", "Create a provider", "Delete state", "Format configuration"], 0,
      "A saved plan lets automation apply the same reviewed set of actions.", diagnostic=True),
    q(117, "terraform", "tf_safety", "What does terraform validate check?",
      ["Configuration syntax and internal consistency", "Whether AWS resources are healthy", "Cloud billing limits", "Every remote state lock"], 0,
      "validate checks configuration, not remote-service health.", diagnostic=True),
    q(118, "terraform", "tf_safety", "A plan shows unexpected resource replacement. What should you do first?",
      ["Stop and investigate the diff", "Apply and repair later", "Delete the state file", "Add -auto-approve"], 0,
      "The plan is a review gate. Understand destructive changes before applying."),

    # Capital Markets — Neeraj
    q(201, "capital_markets", "cm_structure", "What is the primary market?",
      ["Where newly issued securities are sold", "Where investors trade existing securities", "Only the derivatives market", "Only an exchange's closing auction"], 0,
      "Issuers raise capital by selling newly issued securities in the primary market.", diagnostic=True),
    q(202, "capital_markets", "cm_structure", "What happens in the secondary market?",
      ["Investors trade securities already issued", "Companies issue shares for the first time", "Central banks print securities", "Bonds are automatically redeemed"], 0,
      "Secondary-market transactions transfer existing securities between investors.", diagnostic=True),
    q(203, "capital_markets", "cm_structure", "What is the bid–ask spread?",
      ["Difference between the best buying and selling prices", "The annual dividend", "A bond's coupon minus yield", "The daily trading range"], 0,
      "The bid is the best displayed buying price; the ask is the best selling price."),
    q(204, "capital_markets", "cm_equity", "What does owning a common share normally represent?",
      ["A residual ownership interest in a company", "A loan to the government", "A guaranteed dividend", "A futures obligation"], 0,
      "Common equity represents ownership and a residual claim after senior obligations.", diagnostic=True),
    q(205, "capital_markets", "cm_equity", "What does market capitalization measure?",
      ["Share price × shares outstanding", "Revenue minus expenses", "Assets minus liabilities", "Dividend divided by price"], 0,
      "Market capitalization is the market value of outstanding equity.", diagnostic=True),
    q(206, "capital_markets", "cm_equity", "A company earns ₹10 per share and trades at ₹200. What is its P/E ratio?",
      ["20×", "10×", "5×", "₹190"], 0,
      "Price-to-earnings equals price per share divided by earnings per share: 200 ÷ 10 = 20."),
    q(207, "capital_markets", "cm_bonds", "What does a bond coupon represent?",
      ["Contractual interest paid by the issuer", "The bond's equity ownership", "A stock-exchange fee", "The principal repayment date"], 0,
      "The coupon is the bond's stated interest payment.", diagnostic=True),
    q(208, "capital_markets", "cm_bonds", "What usually happens to an existing fixed-rate bond's price when market yields rise?",
      ["It falls", "It rises", "It remains fixed", "It becomes equity"], 0,
      "Existing fixed payments become less attractive when new bonds offer higher yields.", diagnostic=True),
    q(209, "capital_markets", "cm_bonds", "Which bond is generally more sensitive to interest-rate changes?",
      ["A longer-duration bond", "A shorter-duration bond", "A matured bond", "A floating-rate note with immediate reset"], 0,
      "Higher duration indicates greater price sensitivity to yield changes."),
    q(210, "capital_markets", "cm_derivatives", "What right does a call-option buyer receive?",
      ["Buy the underlying at the strike price", "Sell the underlying at the strike price", "Receive every dividend", "Force early bond repayment"], 0,
      "A call gives its buyer the right, but not the obligation, to buy at the strike.", diagnostic=True),
    q(211, "capital_markets", "cm_derivatives", "How does a futures contract differ from an option for the buyer?",
      ["A future creates an obligation; an option gives a right", "A future has no underlying", "An option always costs zero", "Futures cannot settle"], 0,
      "Both futures parties are obligated, while an option buyer may choose whether to exercise.", diagnostic=True),
    q(212, "capital_markets", "cm_derivatives", "An investor owns shares and buys a put on them. What is the likely purpose?",
      ["Protect against downside", "Increase dividend rights", "Remove all risk for free", "Convert shares into bonds"], 0,
      "A protective put can offset some losses below the strike price."),
    q(213, "capital_markets", "cm_risk", "What does diversification primarily reduce?",
      ["Security-specific risk", "All market risk", "Inflation itself", "Every possible loss"], 0,
      "Combining imperfectly correlated assets reduces diversifiable risk.", diagnostic=True),
    q(214, "capital_markets", "cm_risk", "What does equity beta measure?",
      ["Sensitivity to broad market movements", "Guaranteed return", "Accounting profit", "Bond default probability only"], 0,
      "Beta measures how an equity's returns tend to move relative to the market.", diagnostic=True),
    q(215, "capital_markets", "cm_risk", "Why is volatility not identical to permanent loss?",
      ["It measures return dispersion, not the permanence of a decline", "It includes only gains", "Losses cannot be measured", "It applies only to bonds"], 0,
      "Volatility measures variation; it does not identify irreversible impairment."),
    q(216, "capital_markets", "cm_operations", "What is trade settlement?",
      ["Exchange of securities and cash after a trade", "The decision to place an order", "Publication of research", "Calculation of an index only"], 0,
      "Settlement completes delivery of the asset and corresponding payment.", diagnostic=True),
    q(217, "capital_markets", "cm_operations", "What is the role of a clearing house?",
      ["Manage obligations between trading parties", "Issue every listed share", "Set all security prices", "Provide company audits"], 0,
      "A clearing house manages obligations, collateral and counterparty exposure.", diagnostic=True),
    q(218, "capital_markets", "cm_operations", "A trade is executed with the wrong quantity. What is this primarily?",
      ["A trade-booking exception requiring correction", "A market-capitalization change", "A dividend event", "A yield-curve shift"], 0,
      "Incorrect economic details create an operational exception that must be corrected."),
]
